language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e .[dev]
  - pip install --upgrade pytest
script:
  - pytest --cov=mash_client
  - flake8
deploy:
  provider: pypi
  user: "suse-pub-cloud-dev"
  password: $PYPI_PASS
  on:
    tags: true
  skip_existing: true
