.TH "MASH ACCOUNT ADD AZURE" "1" "27-Aug-2018" "" "mash account add azure Manual"
.SH NAME
mash\-account\-add\-azure \- Add Azure account given the provided args.
.SH SYNOPSIS
.B mash account add azure
[OPTIONS] ACCOUNT_NAME CONTAINER_NAME REGION REQUESTING_USER RESOURCE_GROUP STORAGE_ACCOUNT CREDENTIALS_PATH
.SH DESCRIPTION
Add Azure account given the provided args.
.SH OPTIONS
.TP
\fB\-\-group\fP TEXT
Group name to place account in.