.TH "MASH JOB OCI" "1" "2025-05-19" "4.3.0" "mash job oci Manual"
.SH NAME
mash\-job\-oci \- Submit OCI job requests.
.SH SYNOPSIS
.B mash job oci
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Submit OCI job requests.
    
.SH COMMANDS
.PP
\fBadd\fP
  Send add oci job request to mash server...
  See \fBmash job oci-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBschema\fP
  Get the an annotated json dictionary for a...
  See \fBmash job oci-schema(1)\fP for full documentation on the \fBschema\fP command.
