.TH "MASH ACCOUNT AZURE" "1" "2025-05-19" "4.3.0" "mash account azure Manual"
.SH NAME
mash\-account\-azure \- Handle mash azure account requests.
.SH SYNOPSIS
.B mash account azure
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Handle mash azure account requests.
    
.SH COMMANDS
.PP
\fBadd\fP
  Add an Azure account in the user name...
  See \fBmash account azure-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBinfo\fP
  Get info for an Azure account.
  See \fBmash account azure-info(1)\fP for full documentation on the \fBinfo\fP command.
.PP
\fBlist\fP
  Get a list of all Azure accounts.
  See \fBmash account azure-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBdelete\fP
  Delete an azure account in the user name...
  See \fBmash account azure-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBupdate\fP
  Update an Azure account in the user name...
  See \fBmash account azure-update(1)\fP for full documentation on the \fBupdate\fP command.
