.TH "MASH JOB EC2" "1" "2025-05-19" "4.3.0" "mash job ec2 Manual"
.SH NAME
mash\-job\-ec2 \- Submit EC2 job requests.
.SH SYNOPSIS
.B mash job ec2
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Submit EC2 job requests.
    
.SH COMMANDS
.PP
\fBadd\fP
  Send add ec2 job request to mash server...
  See \fBmash job ec2-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBschema\fP
  Get the an annotated json dictionary for a...
  See \fBmash job ec2-schema(1)\fP for full documentation on the \fBschema\fP command.
