.TH "MASH ACCOUNT ALIYUN INFO" "1" "2025-05-19" "4.3.0" "mash account aliyun info Manual"
.SH NAME
mash\-account\-aliyun\-info \- Get info for a Aliyun account.
.SH SYNOPSIS
.B mash account aliyun info
[OPTIONS]
.SH DESCRIPTION
.PP
    Get info for a Aliyun account.
    
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Name of the account.  [required]
