.\" Process this file with
.\" groff -man -Tascii mash-account.1
.\"
.TH "MASH ACCOUNT" "1" "27-Aug-2018" "" "mash account Manual"
.SH NAME
mash\-account \- Handle mash account requests.
.SH SYNOPSIS
.B mash account
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Submit account requests to the \fImash\fP server.
.SH COMMANDS
.PP
\fBadd\fP
  Add an account on the \fImash\fP server. See \fBmash account-add(1)\fP for
  details.
.PP
\fBdelete\fP
  Delete an account from the \fImash\fP server. See
  \fBmash-account-delete(1)\fP details.
.SH AUTHOR
SUSE Public Cloud Team (public-cloud-dev@susecloud.net)

