.TH "MASH ACCOUNT GCE INFO" "1" "22-Nov-2019" "" "mash account gce info Manual"
.SH NAME
mash\-account\-gce\-info \- Get info for a gce account.
.SH SYNOPSIS
.B mash account gce info
[OPTIONS]
.SH DESCRIPTION
Get info for a gce account.
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Name of the account.  [required]
