.TH "MASH ACCOUNT OCI" "1" "2025-05-19" "4.3.0" "mash account oci Manual"
.SH NAME
mash\-account\-oci \- Handle mash OCI account requests.
.SH SYNOPSIS
.B mash account oci
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Handle mash OCI account requests.
    
.SH COMMANDS
.PP
\fBadd\fP
  Add a OCI account in the user name space...
  See \fBmash account oci-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBinfo\fP
  Get info for a OCI account.
  See \fBmash account oci-info(1)\fP for full documentation on the \fBinfo\fP command.
.PP
\fBlist\fP
  Get a list of all oci accounts.
  See \fBmash account oci-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBdelete\fP
  Delete an OCI account in the user name...
  See \fBmash account oci-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBupdate\fP
  Update a OCI account in the user name...
  See \fBmash account oci-update(1)\fP for full documentation on the \fBupdate\fP command.
