.TH "MASH ACCOUNT AZURE INFO" "1" "2025-05-19" "4.3.0" "mash account azure info Manual"
.SH NAME
mash\-account\-azure\-info \- Get info for an Azure account.
.SH SYNOPSIS
.B mash account azure info
[OPTIONS]
.SH DESCRIPTION
.PP
    Get info for an Azure account.
    
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Name of the account.  [required]
