.TH "MASH CONFIG" "1" "2025-05-19" "4.3.0" "mash config Manual"
.SH NAME
mash\-config \- Provides commands to setup and view client...
.SH SYNOPSIS
.B mash config
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Provides commands to setup and view client configuration file.
    
.SH COMMANDS
.PP
\fBsetup\fP
  Create a configuration file for the mash...
  See \fBmash config-setup(1)\fP for full documentation on the \fBsetup\fP command.
.PP
\fBshow\fP
  Prints a dictionary from the client config...
  See \fBmash config-show(1)\fP for full documentation on the \fBshow\fP command.
