.TH "MASH JOB INFO" "1" "2025-05-19" "4.3.0" "mash job info Manual"
.SH NAME
mash\-job\-info \- Get info for a job in the MASH server...
.SH SYNOPSIS
.B mash job info
[OPTIONS]
.SH DESCRIPTION
.PP
    Get info for a job in the MASH server pipeline.
    
.SH OPTIONS
.TP
\fB\-\-show\-data\fP
Include all status info for the job.
.TP
\fB\-\-job\-id\fP UUID
The UUID of the job to retrieve.  [required]
