.TH "MASH JOB GCE" "1" "2025-05-19" "4.3.0" "mash job gce Manual"
.SH NAME
mash\-job\-gce \- Submit GCE job requests.
.SH SYNOPSIS
.B mash job gce
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Submit GCE job requests.
    
.SH COMMANDS
.PP
\fBadd\fP
  Send add gce job request to mash server...
  See \fBmash job gce-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBschema\fP
  Get the an annotated json dictionary for a...
  See \fBmash job gce-schema(1)\fP for full documentation on the \fBschema\fP command.
