.TH "MASH JOB OCI ADD" "1" "2025-05-19" "4.3.0" "mash job oci add Manual"
.SH NAME
mash\-job\-oci\-add \- Send add oci job request to mash server...
.SH SYNOPSIS
.B mash job oci add
[OPTIONS] DOCUMENT
.SH DESCRIPTION
.PP
    Send add oci job request to mash server based on provided json document.
    
.SH OPTIONS
.TP
\fB\-\-dry\-run\fP
Validate job document but do not create job.
.TP
\fB\-\-api\-version\fP [v1]
The version of the API to use for request. Defaults to the latest API version based on client version.
