.TH "MASH JOB LIST" "1" "2025-05-19" "4.3.0" "mash job list Manual"
.SH NAME
mash\-job\-list \- List all jobs in the MASH server pipeline.
.SH SYNOPSIS
.B mash job list
[OPTIONS]
.SH DESCRIPTION
.PP
    List all jobs in the MASH server pipeline.
    
.SH OPTIONS
.TP
\fB\-\-page\fP INTEGER
The page number of results to return.
.TP
\fB\-\-per\-page\fP INTEGER
The number of results to return per page.
.TP
\fB\-\-api\-version\fP [v1]
The version of the API to use for request. Defaults to the latest API version based on client version.
