.\" Process this file with
.\" groff -man -Tascii mash-job-delete.1
.\"
.TH "MASH JOB DELETE" "1" "27-Aug-2018" "" "mash job delete Manual"
.SH NAME
mash\-job\-delete \- Delete a job from the mash server pipeline
.SH SYNOPSIS
.B mash job delete
[OPTIONS]
.SH DESCRIPTION
Delete the job with the given ID from the \fImash\fP server pipeline
.SH OPTIONS
.TP
\fB--job-id\fP JOB_ID
Provide the UUID of the job to be removed from the \fImash\fP server pipeline
.SH AUTHOR
SUSE Public Cloud Team (public-cloud-dev@susecloud.net)
