.TH "MASH ACCOUNT EC2 INFO" "1" "2025-05-19" "4.3.0" "mash account ec2 info Manual"
.SH NAME
mash\-account\-ec2\-info \- Get info for an ec2 account.
.SH SYNOPSIS
.B mash account ec2 info
[OPTIONS]
.SH DESCRIPTION
.PP
    Get info for an ec2 account.
    
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Name of the account.  [required]
