.TH "MASH JOB AZURE ADD" "1" "2025-05-19" "4.3.0" "mash job azure add Manual"
.SH NAME
mash\-job\-azure\-add \- Send add azure job request to mash server...
.SH SYNOPSIS
.B mash job azure add
[OPTIONS] DOCUMENT
.SH DESCRIPTION
.PP
    Send add azure job request to mash server based on provided json document.
    
.SH OPTIONS
.TP
\fB\-\-dry\-run\fP
Validate job document but do not create job.
.TP
\fB\-\-api\-version\fP [v1]
The version of the API to use for request. Defaults to the latest API version based on client version.
