.TH "MASH USER PASSWORD RESET" "1" "2025-05-19" "4.3.0" "mash user password reset Manual"
.SH NAME
mash\-user\-password\-reset \- Initialize password reset for user.
.SH SYNOPSIS
.B mash user password reset
[OPTIONS]
.SH DESCRIPTION
.PP
    Initialize password reset for user.
    
.SH OPTIONS
.TP
\fB\-\-email\fP TEXT
The email for the mash user (default taken from config).
