.TH "MASH ACCOUNT EC2 DELETE" "1" "2025-05-19" "4.3.0" "mash account ec2 delete Manual"
.SH NAME
mash\-account\-ec2\-delete \- Delete an ec2 account in the user name...
.SH SYNOPSIS
.B mash account ec2 delete
[OPTIONS]
.SH DESCRIPTION
.PP
    Delete an ec2 account in the user name space on the MASH server.
    
.SH OPTIONS
.TP
\fB\-\-force\fP
Force deletion without prompt.
.TP
\fB\-\-name\fP TEXT
Name of the account to be deleted.  [required]
