.TH "MASH USER CREATE" "1" "2025-05-19" "4.3.0" "mash user create Manual"
.SH NAME
mash\-user\-create \- Handle mash user creation requests.
.SH SYNOPSIS
.B mash user create
[OPTIONS]
.SH DESCRIPTION
.PP
    Handle mash user creation requests.
    
.SH OPTIONS
.TP
\fB\-\-email\fP TEXT
The email address for the mash user.  [required]
.TP
\fB\-\-password\fP TEXT
[required]
