.TH "MASH JOB AZURE" "1" "22-Nov-2019" "" "mash job azure Manual"
.SH NAME
mash\-job\-azure \- Submit Azure job requests.
.SH SYNOPSIS
.B mash job azure
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Submit Azure job requests.
.SH COMMANDS
.PP
\fBadd\fP
  Send add azure job request to mash server...
  See \fBmash job azure-add(1)\fP for full documentation on the \fBadd\fP command.
