.TH "MASH ACCOUNT" "1" "2025-05-19" "4.3.0" "mash account Manual"
.SH NAME
mash\-account \- Submit account requests to the MASH server.
.SH SYNOPSIS
.B mash account
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Submit account requests to the MASH server.
    
.SH COMMANDS
.PP
\fBazure\fP
  Handle mash azure account requests.
  See \fBmash account-azure(1)\fP for full documentation on the \fBazure\fP command.
.PP
\fBec2\fP
  Handle mash ec2 account requests.
  See \fBmash account-ec2(1)\fP for full documentation on the \fBec2\fP command.
.PP
\fBgce\fP
  Handle mash gce account requests.
  See \fBmash account-gce(1)\fP for full documentation on the \fBgce\fP command.
.PP
\fBoci\fP
  Handle mash OCI account requests.
  See \fBmash account-oci(1)\fP for full documentation on the \fBoci\fP command.
.PP
\fBaliyun\fP
  Handle mash Aliyun account requests.
  See \fBmash account-aliyun(1)\fP for full documentation on the \fBaliyun\fP command.
