.TH "MASH ACCOUNT ADD" "1" "27-Aug-2018" "" "mash account add Manual"
.SH NAME
mash\-account\-add \- Handle mash account add requests.
.SH SYNOPSIS
.B mash account add
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Handle mash account add requests.
.SH COMMANDS
.PP
\fBec2\fP
  Add EC2 account given the provided args.
  See \fBmash account add-ec2(1)\fP for full documentation on the \fBec2\fP command.
.PP
\fBazure\fP
  Add Azure account given the provided args.
  See \fBmash account add-azure(1)\fP for full documentation on the \fBazure\fP command.