.TH "MASH JOB DELETE" "1" "2025-05-19" "4.3.0" "mash job delete Manual"
.SH NAME
mash\-job\-delete \- Delete the job with the given ID from the...
.SH SYNOPSIS
.B mash job delete
[OPTIONS]
.SH DESCRIPTION
.PP
    Delete the job with the given ID from the MASH server pipeline.
    
.SH OPTIONS
.TP
\fB\-\-force\fP
Force deletion without prompt.
.TP
\fB\-\-job\-id\fP UUID
The UUID of the job to be removed from the MASH server pipeline.  [required]
