.TH "MASH USER PASSWORD" "1" "2025-05-19" "4.3.0" "mash user password Manual"
.SH NAME
mash\-user\-password \- Submit user password requests.
.SH SYNOPSIS
.B mash user password
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Submit user password requests.
    
.SH COMMANDS
.PP
\fBreset\fP
  Initialize password reset for user.
  See \fBmash user password-reset(1)\fP for full documentation on the \fBreset\fP command.
.PP
\fBchange\fP
  Change password for user.
  See \fBmash user password-change(1)\fP for full documentation on the \fBchange\fP command.
