.TH "MASH ACCOUNT ALIYUN DELETE" "1" "2025-05-19" "4.3.0" "mash account aliyun delete Manual"
.SH NAME
mash\-account\-aliyun\-delete \- Delete an Aliyun account in the user name...
.SH SYNOPSIS
.B mash account aliyun delete
[OPTIONS]
.SH DESCRIPTION
.PP
    Delete an Aliyun account in the user name space on the MASH server.
    
.SH OPTIONS
.TP
\fB\-\-force\fP
Force deletion without prompt.
.TP
\fB\-\-name\fP TEXT
Name of the account to be deleted.  [required]
