.TH "MASH JOB AZURE SCHEMA" "1" "2025-05-19" "4.3.0" "mash job azure schema Manual"
.SH NAME
mash\-job\-azure\-schema \- Get the an annotated json dictionary for a...
.SH SYNOPSIS
.B mash job azure schema
[OPTIONS]
.SH DESCRIPTION
.PP
    Get the an annotated json dictionary for a Azure job.
    
.SH OPTIONS
.TP
\fB\-\-json\fP
Prints an example json dictionary with example values.
.TP
\fB\-\-raw\fP
Prints a raw jsonschema dictionary.
.TP
\fB\-\-annotated\fP
Prints a raw jsonschema dictionary.
