.TH "MASH AUTH TOKEN INFO" "1" "2025-05-19" "4.3.0" "mash auth token info Manual"
.SH NAME
mash\-auth\-token\-info \- Return information for token matching jti.
.SH SYNOPSIS
.B mash auth token info
[OPTIONS]
.SH DESCRIPTION
.PP
    Return information for token matching jti.
    
.SH OPTIONS
.TP
\fB\-\-jti\fP TEXT
The token jti UUID.  [required]
