.TH "MASH ACCOUNT DELETE" "1" "27-Aug-2018" "" "mash account delete Manual"
.SH NAME
mash\-account\-delete \- Delete account given input.
.SH SYNOPSIS
.B mash account delete
[OPTIONS] ACCOUNT_NAME PROVIDER REQUESTING_USER
.SH DESCRIPTION
Delete account given input.
.SH OPTIONS
.TP
\fB\-\-delete\fP
.PP