.TH "MASH USER PASSWORD CHANGE" "1" "2025-05-19" "4.3.0" "mash user password change Manual"
.SH NAME
mash\-user\-password\-change \- Change password for user.
.SH SYNOPSIS
.B mash user password change
[OPTIONS]
.SH DESCRIPTION
.PP
    Change password for user.
    
.SH OPTIONS
.TP
\fB\-\-email\fP TEXT
The email for the mash user (default taken from config).
