.TH "MASH USER CREATE" "1" "22-Nov-2019" "" "mash user create Manual"
.SH NAME
mash\-user\-create \- Handle mash user creation requests.
.SH SYNOPSIS
.B mash user create
[OPTIONS]
.SH DESCRIPTION
Handle mash user creation requests.
.SH OPTIONS
.TP
\fB\-\-username\fP TEXT
The username for the mash user.  [required]
.TP
\fB\-\-email\fP TEXT
The email address for the mash user.  [required]
