.TH "MASH ACCOUNT GCE" "1" "2025-05-19" "4.3.0" "mash account gce Manual"
.SH NAME
mash\-account\-gce \- Handle mash gce account requests.
.SH SYNOPSIS
.B mash account gce
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Handle mash gce account requests.
    
.SH COMMANDS
.PP
\fBadd\fP
  Add a GCE account in the user name space...
  See \fBmash account gce-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBinfo\fP
  Get info for a gce account.
  See \fBmash account gce-info(1)\fP for full documentation on the \fBinfo\fP command.
.PP
\fBlist\fP
  Get a list of all gce accounts.
  See \fBmash account gce-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBdelete\fP
  Delete an gce account in the user name...
  See \fBmash account gce-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBupdate\fP
  Update a GCE account in the user name...
  See \fBmash account gce-update(1)\fP for full documentation on the \fBupdate\fP command.
