.TH "MASH ACCOUNT OCI INFO" "1" "2025-05-19" "4.3.0" "mash account oci info Manual"
.SH NAME
mash\-account\-oci\-info \- Get info for a OCI account.
.SH SYNOPSIS
.B mash account oci info
[OPTIONS]
.SH DESCRIPTION
.PP
    Get info for a OCI account.
    
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Name of the account.  [required]
