.TH "MASH ACCOUNT ALIYUN UPDATE" "1" "2025-05-19" "4.3.0" "mash account aliyun update Manual"
.SH NAME
mash\-account\-aliyun\-update \- Update a Aliyun account in the user name...
.SH SYNOPSIS
.B mash account aliyun update
[OPTIONS]
.SH DESCRIPTION
.PP
    Update a Aliyun account in the user name space on the MASH server.
    
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Name for the account to update.  [required]
.TP
\fB\-\-bucket\fP TEXT
The storage bucket where images will be uploaded.
.TP
\fB\-\-region\fP TEXT
The region where the test instances will be launched.
.TP
\fB\-\-security\-group\-id\fP TEXT
The security group ID that will be used for launching test instances.
.TP
\fB\-\-vswitch\-id\fP TEXT
The vswitch ID that will be used for launching test instances.
.TP
\fB\-\-access\-key\fP TEXT
Aliyun access key.
.TP
\fB\-\-access\-secret\fP TEXT
Aliyun access key secret.
