.TH "MASH JOB" "1" "27-Aug-2018" "" "mash job Manual"
.SH NAME
mash\-job \- Handle mash job requests.
.SH SYNOPSIS
.B mash job
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Handle mash job requests.
.SH COMMANDS
.PP
\fBadd\fP
  Send add job request to mash server based on...
  See \fBmash job-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBdelete\fP
  Delete a job given the UUID.
  See \fBmash job-delete(1)\fP for full documentation on the \fBdelete\fP command.