.TH "MASH JOB EC2" "1" "22-Nov-2019" "" "mash job ec2 Manual"
.SH NAME
mash\-job\-ec2 \- Submit EC2 job requests.
.SH SYNOPSIS
.B mash job ec2
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Submit EC2 job requests.
.SH COMMANDS
.PP
\fBadd\fP
  Send add ec2 job request to mash server based...
  See \fBmash job ec2-add(1)\fP for full documentation on the \fBadd\fP command.
