.TH "MASH ACCOUNT ALIYUN" "1" "2025-05-19" "4.3.0" "mash account aliyun Manual"
.SH NAME
mash\-account\-aliyun \- Handle mash Aliyun account requests.
.SH SYNOPSIS
.B mash account aliyun
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Handle mash Aliyun account requests.
    
.SH COMMANDS
.PP
\fBadd\fP
  Add a Aliyun account in the user name...
  See \fBmash account aliyun-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBinfo\fP
  Get info for a Aliyun account.
  See \fBmash account aliyun-info(1)\fP for full documentation on the \fBinfo\fP command.
.PP
\fBlist\fP
  Get a list of all Aliyun accounts.
  See \fBmash account aliyun-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBdelete\fP
  Delete an Aliyun account in the user name...
  See \fBmash account aliyun-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBupdate\fP
  Update a Aliyun account in the user name...
  See \fBmash account aliyun-update(1)\fP for full documentation on the \fBupdate\fP command.
