.TH "MASH ACCOUNT OCI DELETE" "1" "2025-05-19" "4.3.0" "mash account oci delete Manual"
.SH NAME
mash\-account\-oci\-delete \- Delete an OCI account in the user name...
.SH SYNOPSIS
.B mash account oci delete
[OPTIONS]
.SH DESCRIPTION
.PP
    Delete an OCI account in the user name space on the MASH server.
    
.SH OPTIONS
.TP
\fB\-\-force\fP
Force deletion without prompt.
.TP
\fB\-\-name\fP TEXT
Name of the account to be deleted.  [required]
