.TH "MASH AUTH TOKEN REFRESH" "1" "2025-05-19" "4.3.0" "mash auth token refresh Manual"
.SH NAME
mash\-auth\-token\-refresh \- Handle token refresh.
.SH SYNOPSIS
.B mash auth token refresh
[OPTIONS]
.SH DESCRIPTION
.PP
    Handle token refresh.
.PP
    Get a new access token using current refresh token.
    
