.TH "MASH JOB AZURE" "1" "2025-05-19" "4.3.0" "mash job azure Manual"
.SH NAME
mash\-job\-azure \- Submit Azure job requests.
.SH SYNOPSIS
.B mash job azure
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Submit Azure job requests.
    
.SH COMMANDS
.PP
\fBadd\fP
  Send add azure job request to mash server...
  See \fBmash job azure-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBschema\fP
  Get the an annotated json dictionary for a...
  See \fBmash job azure-schema(1)\fP for full documentation on the \fBschema\fP command.
