.TH "MASH ACCOUNT GCE INFO" "1" "2025-05-19" "4.3.0" "mash account gce info Manual"
.SH NAME
mash\-account\-gce\-info \- Get info for a gce account.
.SH SYNOPSIS
.B mash account gce info
[OPTIONS]
.SH DESCRIPTION
.PP
    Get info for a gce account.
    
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Name of the account.  [required]
