.TH "MASH ACCOUNT" "1" "27-Aug-2018" "" "mash account Manual"
.SH NAME
mash\-account \- Handle mash account requests.
.SH SYNOPSIS
.B mash account
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Handle mash account requests.
.SH COMMANDS
.PP
\fBdelete\fP
  Delete account given input.
  See \fBmash account-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBadd\fP
  Handle mash account add requests.
  See \fBmash account-add(1)\fP for full documentation on the \fBadd\fP command.