.TH "MASH AUTH TOKEN DELETE" "1" "2025-05-19" "4.3.0" "mash auth token delete Manual"
.SH NAME
mash\-auth\-token\-delete \- If no jti is provided delete all tokens.
.SH SYNOPSIS
.B mash auth token delete
[OPTIONS]
.SH DESCRIPTION
.PP
    If no jti is provided delete all tokens.
.PP
    Otherwise delete token matching the jti.
    
.SH OPTIONS
.TP
\fB\-\-jti\fP TEXT
The token jti UUID.
