.TH "MASH AUTH" "1" "2025-05-19" "4.3.0" "mash auth Manual"
.SH NAME
mash\-auth \- Submit authentication requests.
.SH SYNOPSIS
.B mash auth
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Submit authentication requests.
    
.SH COMMANDS
.PP
\fBlogin\fP
  Handle mash user login.
  See \fBmash auth-login(1)\fP for full documentation on the \fBlogin\fP command.
.PP
\fBlogout\fP
  Handle mash user logout.
  See \fBmash auth-logout(1)\fP for full documentation on the \fBlogout\fP command.
.PP
\fBtoken\fP
  Submit token requests.
  See \fBmash auth-token(1)\fP for full documentation on the \fBtoken\fP command.
.PP
\fBoidc\fP
  Handle mash OpenID Connect authentication.
  See \fBmash auth-oidc(1)\fP for full documentation on the \fBoidc\fP command.
