.TH "MASH JOB ALIYUN" "1" "2025-05-19" "4.3.0" "mash job aliyun Manual"
.SH NAME
mash\-job\-aliyun \- Submit Aliyun job requests.
.SH SYNOPSIS
.B mash job aliyun
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Submit Aliyun job requests.
    
.SH COMMANDS
.PP
\fBadd\fP
  Send add Aliyun job request to server...
  See \fBmash job aliyun-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBschema\fP
  Get the an annotated json dictionary for a...
  See \fBmash job aliyun-schema(1)\fP for full documentation on the \fBschema\fP command.
