.TH "MASH USER" "1" "2025-05-19" "4.3.0" "mash user Manual"
.SH NAME
mash\-user \- Submit user requests.
.SH SYNOPSIS
.B mash user
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Submit user requests.
    
.SH COMMANDS
.PP
\fBcreate\fP
  Handle mash user creation requests.
  See \fBmash user-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBinfo\fP
  Get mash user info.
  See \fBmash user-info(1)\fP for full documentation on the \fBinfo\fP command.
.PP
\fBdelete\fP
  Handle mash user deletion requests.
  See \fBmash user-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBpassword\fP
  Submit user password requests.
  See \fBmash user-password(1)\fP for full documentation on the \fBpassword\fP command.
