.TH "MASH JOB GCE" "1" "22-Nov-2019" "" "mash job gce Manual"
.SH NAME
mash\-job\-gce \- Submit GCE job requests.
.SH SYNOPSIS
.B mash job gce
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Submit GCE job requests.
.SH COMMANDS
.PP
\fBadd\fP
  Send add gce job request to mash server based...
  See \fBmash job gce-add(1)\fP for full documentation on the \fBadd\fP command.
