.TH "MASH ACCOUNT EC2" "1" "2025-05-19" "4.3.0" "mash account ec2 Manual"
.SH NAME
mash\-account\-ec2 \- Handle mash ec2 account requests.
.SH SYNOPSIS
.B mash account ec2
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Handle mash ec2 account requests.
    
.SH COMMANDS
.PP
\fBadd\fP
  Add an EC2 account in the user name space...
  See \fBmash account ec2-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBinfo\fP
  Get info for an ec2 account.
  See \fBmash account ec2-info(1)\fP for full documentation on the \fBinfo\fP command.
.PP
\fBlist\fP
  Get a list of all ec2 accounts.
  See \fBmash account ec2-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBdelete\fP
  Delete an ec2 account in the user name...
  See \fBmash account ec2-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBupdate\fP
  Update an EC2 account in the user name...
  See \fBmash account ec2-update(1)\fP for full documentation on the \fBupdate\fP command.
